### ISSUE TITLE
omegaconf 2.1.0 has a non-standard dependency specifier PyYAML>=5.1.*.

### ISSUE THREAD

**Issue by Amazon90** [omry/omegaconf#1107]
**Describe the bug**
https://github.com/oobabooga/text-generation-webui/issues/3261
https://github.com/pypa/pip/issues/12063#issuecomment-1647244895
pip developers told me to contact omagaconf project to fix this issue
Please check the issue at the link, thanks.

**Comment by odelalleau** [comment]
Thanks for reporting, but this has already been fixed in 2.1.1 (see #758)

**Comment by Amazon90** [comment]
![企业微信截图_20230724194734](https://github.com/omry/omegaconf/assets/72290820/65ca7d26-e847-4024-8c0a-3c13020bcf14)
It seems that there is a version conflict, but I don't know how to solve this, hope you can help me, thank you.

**Comment by Amazon90** [comment]
> Thanks for reporting, but this has already been fixed in 2.1.1 (see #758)
![企业微信截图_20230724194734](https://github.com/omry/omegaconf/assets/72290820/17c7d3cf-8566-4267-a8f5-048b926f6495)
```
ERROR: 
pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fairseq 0.12.2 requires omegaconf<2.1, but you have omegaconf 2.1.1 which is incompatible.
hydra-core 1.0.7 requires omegaconf<2.1,>=2.0.5, but you have omegaconf 2.1.1 which is incompatible.
```
It seems that there is a version conflict, but I don't know how to solve this, hope you can help me, thank you.

**Comment by odelalleau** [comment]
> hydra-core 1.0.7 requires omegaconf<2.1,>=2.0.5

Upgrade Hydra to a more recent version. Be aware that this may require some changes to your code though (see https://hydra.cc/docs/upgrades/intro/)

**Comment by Amazon90** [comment]
> > hydra-core 1.0.7 requires omegaconf<2.1,>=2.0.5
> 
> Upgrade Hydra to a more recent version. Be aware that this may require some changes to your code though (see https://hydra.cc/docs/upgrades/intro/)

![企业微信截图_20230725140132](https://github.com/omry/omegaconf/assets/72290820/a95d501f-8144-443c-b395-1e7d601c2274)
![企业微信截图_20230725140124](https://github.com/omry/omegaconf/assets/72290820/45f95b9a-1146-4cbd-873b-8d9330d1bc6c)

Upgrading Hydra does not fix this issue

**Comment by odelalleau** [comment]
> Upgrading Hydra does not fix this issue

I see `pip install hydra-core==1.0.7` so I'm a bit confused as to what you mean.

It seems like you may be trying to use fairseq, which appears to be incompatible with Hydra 1.1+

**Comment by Amazon90** [comment]
I upgraded hydra-core according to your suggestion, but got an error:
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7
I have no choice but to reinstall back to 1.0.7, the previous problem still exists
omegaconf 2.1.0 has a non-standard dependency specifier PyYAML>=5.1.*.

**Comment by Amazon90** [comment]
> > Upgrading Hydra does not fix this issue
> 
> I see `pip install hydra-core==1.0.7` so I'm a bit confused as to what you mean.
> 
> It seems like you may be trying to use fairseq, which appears to be incompatible with Hydra 1.1+

I upgraded hydra-core according to your suggestion, but got an error:
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7
I have no choice but to reinstall back to 1.0.7, the previous problem still exists
omegaconf 2.1.0 has a non-standard dependency specifier PyYAML>=5.1.*.

**Comment by odelalleau** [comment]
Right, so if you really want to not see this message (not sure if it’s an error or just a warning), you could create your own fork of OmegaConf 2.1, grab the fix from #761, install it first, and hopefully fairseq will install without complaining.

**Comment by omry** [comment]
You can also nudge the fairseq folks about supporting the latest version of Hydra.

**Comment by songnan1111** [comment]
I also have the same problem. Have you solved it now? How did you solve it?
